name: test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - cudatoolkit-dev=11.7.0=h1fa729e_5
  - dask-core=2022.7.0=py310h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.6.0.25=0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.6.0.25=0
  - libcufile-dev=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcurl=7.87.0=h91b91d3_0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2023.1.0.15=0
  - numpy-base=1.23.5=py310h8e6c178_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1t=h7f8727e_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.10.9=h7a1cb2a_2
  - pytorch=1.13.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.40.1=h5082296_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing_extensions=4.4.0=py310h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - annoy==1.17.2
    - antlr4-python3-runtime==4.9.3
    - attrs==22.2.0
    - av==10.0.0
    - black==23.3.0
    - boto3==1.26.116
    - botocore==1.29.116
    - brotlipy==0.7.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - click==8.1.3
    - cloudpickle==2.2.1
    - contourpy==1.0.7
    - cryptography==39.0.1
    - cupy-cuda11x==11.6.0
    - cycler==0.11.0
    - cytoolz==0.12.0
    - dask==2022.7.0
    - detectron2==0.6
    - detectron2-densepose==0.6
    - fastrlock==0.8.1
    - flatbuffers==23.3.3
    - fonttools==4.39.0
    - fsspec==2022.11.0
    - fvcore==0.1.5.post20221221
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.3
    - hydra-core==1.3.2
    - idna==3.4
    - imagecodecs==2021.8.26
    - imageio==2.19.3
    - iopath==0.1.9
    - jmespath==1.0.1
    - kiwisolver==1.4.4
    - locket==1.0.0
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mediapipe==0.9.2.1
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - mypy-extensions==1.0.0
    - networkx==2.8.4
    - ninja==1.11.1
    - numpy==1.23.5
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - opencv-contrib-python==4.7.0.72
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - packaging==23.0
    - pathspec==0.11.1
    - pillow==9.4.0
    - pip==23.0.1
    - platformdirs==3.2.0
    - portalocker==2.7.0
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pydantic==1.10.7
    - pygments==2.15.1
    - pyhocon==0.3.60
    - pyopenssl==23.0.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytorch-fid==0.3.0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==13.3.4
    - rsa==4.9
    - s3transfer==0.6.0
    - scikit-image==0.19.3
    - scipy==1.10.1
    - setuptools==65.6.3
    - tabulate==0.9.0
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - tensorfn==0.1.28
    - termcolor==2.2.0
    - thop==0.1.1-2305142158
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1
    - typing-extensions==4.4.0
    - urllib3==1.26.14
    - werkzeug==2.2.3
    - wheel==0.38.4
    - yacs==0.1.8
prefix: /opt/conda/envs/test
